import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "../components/BlogCard";
const graphcms = new GraphQLClient(
  "https://api-ap-south-1.hygraph.com/v2/clik3yhnn07yk01t756ice2na/master"
);
const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;
export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  console.log("wtssss", posts);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}
const inter = Inter({ subsets: ["latin"] });

export default function Home({ posts }) {
  return (
    <div
      style={{
        backgroundColor: "white",
        // backgroundImage:
        //   "url(https://helpx.adobe.com/content/dam/help/en/photoshop/using/convert-color-image-black-white/jcr_content/main-pars/before_and_after/image-before/Landscape-Color.jpg)",
      }}
    >
      <Head>
        <title>create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-between p-24 ${inter.className}`}
      >
        {posts.map((post) => (
          <BlogCard
            title={post.title}
            author={post.author}
            coverPhoto={post.coverPhoto}
            key={post.id}
            datePublished={post.datePublished}
            slug={post.slug}
          />
        ))}
      </main>
    </div>
  );
}
